/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.wlezzar.doks

import kotlinx.coroutines.ExperimentalCoroutinesApi

@ExperimentalCoroutinesApi
fun main(args: Array<String>): Unit = Doks().main(args)