name: Publish docker images

on:
  release:
    types: [ "published" ]

jobs:

  publish-docker:
    name: Publish docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '100'

      - run: git fetch --all --depth=100 --tags

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: publish zoe images
        run: |
          ./gradlew test doks-core:dockerPush